### ISSUE TITLE
Getting error on production but local is not happening this error

### ISSUE THREAD

**Issue by raymondugv** [codezero-be/laravel-localized-routes#24]
Hi, 

I'm using laravel 5.6 and I've received this error screen when published the code to staging and production server, but on localhost, it works very well. 

![image](https://user-images.githubusercontent.com/21214764/75147510-10cae300-5730-11ea-8c9a-c78217126e98.png)

Could you please show me how to fix this or what is the information you need to help me on this matter?.

Thank you.

**Comment by ivanvermeyen** [comment]
Hello,

If I understand it correctly, the router is not finding the `localized` macro for some reason.
It's a bit of a tough one to reproduce, because I'm already running tests for each Laravel / PHP version from 5.6 / 7.1 and up.

Do route macro's work at all in your app?
Is the ServiceProvider being discovered?

Can you reproduce the issue in a new app so I can take a look at it and see if I find anything unusual?

**Comment by raymondugv** [comment]
Hi @ivanvermeyen , 

Thank for your reply. 
This is my Service Providers
![image](https://user-images.githubusercontent.com/21214764/75208588-bd4baa00-57ae-11ea-85c2-a41d3dde3f3d.png)

Since I'm a newbie in Laravel developing, could you please show me how to check it?

**Comment by raymondugv** [comment]
I've made it work by running `composer dumpautoload`. 

and it works like a charm.

**Comment by ivanvermeyen** [comment]
Nice to hear that it's working :)
Dump autoload has saved me a few times in the past as well :)
